### ISSUE TITLE
HTTP POST Request

### ISSUE THREAD

**Issue by damongolding** [soypat/cyw43439#44]
Would it be possible to implement POST requests?

My end goal would be to update Home Assistant via the REST api but they only accept POST requests when updating.

**Comment by soypat** [comment]
I've added a couple of hints on how to send a POST request. Basically it requires doing the same thing as a GET but the POST has the additional feature of being able to include data after the HTTP header, which you can simply append to the header byte slice.
https://github.com/soypat/cyw43439/blob/1401aecdd7441ae1c77b8fe66fb68727e5439c9d/examples/http-client/main.go#L75-L76

**Comment by damongolding** [comment]
Amazing thank you 🙏

I was able to add a auth header (I believe) but I was stuck on sending the data.

**Comment by soypat** [comment]
Hey @damongolding,  I believe this is solved then?
